version: '3.2'
services:
  webdav:
    build: .
    image: matir/webdav
    restart: always
    ports:
      - "9443:443"
    env_file:
      - ./webdav.env
    volumes:
      - type: bind
        source: ~/Shared
        target: /srv/dav
