apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws
  labels:
    app: ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws
  template:
    metadata:
      labels:
        app: ws
    spec:
      containers:
      - name: ws
        image: matir/debdeb
        command: ["/bin/bash"]
        args: ["-c", "sleep infinity"]
