[tools]
python = "3.14"
uv = "latest"

[env]
_.file = '.env'
_.python.venv = ".venv"

[tasks.test]
run = "uv run pytest tests"

[tasks.typecheck]
description = "Run mypy type checking"
run = "uv run mypy src"

[tasks.lint]
run = "uv run ruff check ."

[tasks.check]
description = "Run all lints and tests"
depends = ["lint", "typecheck", "test"]

[tasks.format]
run = "uv run ruff format ."

[tasks.coverage]
run = "uv run pytest --cov=src/trashdig tests"

[tasks.run]
run = "uv run trashdig"
